"""
Constants and mappings for PDF salary contract extraction
"""
from typing import Dict, Tuple

# Roman numeral conversion
ROMAN_NUMERAL_VALUES = {
    'I': 1,
    'V': 5,
    'X': 10,
    'L': 50,
    'C': 100,
    'D': 500,
    'M': 1000,
}

# Education level and credits mapping
# Maps various text representations to (education_level, credits) tuples
EDU_MAP_RAW: Dict[str, Tuple[str, int]] = {
    'BA': ('B', 0),
    'B': ('B', 0),
    'BA0': ('B', 0),
    'BA+0': ('B', 0),
    'BACHELOR': ('B', 0),
    'BA+10': ('B', 10),
    'B+10': ('B', 10),
    'BA+15': ('B', 15),
    'B+15': ('B', 15),
    '15': ('B', 15),
    'BA+20': ('B', 20),
    'B+20': ('B', 20),
    'BA+30': ('B', 30),
    'B+30': ('B', 30),
    'B30': ('B', 30),
    'B30/MA': ('M', 0),
    'BA+45': ('B', 45),
    'B+45': ('B', 45),
    'BA+60': ('B', 60),
    'MA': ('M', 0),
    'M': ('M', 0),
    'MA0': ('M', 0),
    'MA+0': ('M', 0),
    'MASTERS': ('M', 0),
    'MA+10': ('M', 10),
    'M+10': ('M', 10),
    'MA+15': ('M', 15),
    'M+15': ('M', 15),
    'MA+20': ('M', 20),
    'M+20': ('M', 20),
    'MA+30': ('M', 30),
    'M+30': ('M', 30),
    'MA+45': ('M', 45),
    'M+45': ('M', 45),
    'MA+45/CAGS': ('M', 45),
    'M+45/CAGS': ('M', 45),
    'MA+45CAGS': ('M', 45),
    'MA+40': ('M', 40),
    'M+40': ('M', 40),
    'MA+60': ('M', 60),
    'M+60': ('M', 60),
    'MA+60/CAGS': ('M', 60),
    'M+60/CAGS': ('M', 60),
    'MA+60CAGS': ('M', 60),
    'CAGS': ('M', 60),
    'CAGS/DOC': ('D', 0),
    'CAGS DOC': ('D', 0),
    'DOC': ('D', 0),
    'DOCTORATE': ('D', 0),
    'PHD': ('D', 0),
    'EDD': ('D', 0),
    'PROV': ('D', 0),
    'AS': ('B', 0),
    'LANE1': ('B', 0),
    'LANE2': ('B', 15),
    'LANE3': ('B', 30),
    'LANE4': ('M', 0),
    'LANE5': ('M', 15),
    'LANE6': ('M', 30),
    'LANE7': ('M', 45),
    'LANE8': ('M', 60),
    'PAYSCALE1': ('B', 0),
    'PAYSCALE2': ('B', 15),
    'PAYSCALE3': ('B', 30),
    'PAYSCALE4': ('M', 0),
    'PAYSCALE5': ('M', 15),
    'PAYSCALE6': ('M', 30),
    # Roman numeral variants (for tables using I, II, III, IV notation)
    'I': ('B', 0),
    'II': ('B', 15),
    'III': ('B', 30),
    'IV': ('M', 0),
    'V': ('M', 15),
    'VI': ('M', 30),
    'VII': ('M', 45),
    'VIII': ('M', 60),
    '(I)': ('B', 0),
    '(II)': ('B', 15),
    '(III)': ('B', 30),
    '(IV)': ('M', 0),
    '(V)': ('M', 15),
    '(VI)': ('M', 30),
    '(VII)': ('M', 45),
    '(VIII)': ('M', 60),
}
